source "https://rubygems.org"

gem "logger"
gem "csv"
gem "base64"
gem "bigdecimal"

group :jekyll_plugins do
  gem "jekyll-bookshop", "2.2.2"
  gem "cloudcannon-jekyll-bookshop", "2.2.2"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "webrick"
end